export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const FETCH_MOVIE_DETAILS_REQUEST = "FETCH_MOVIE_DETAILS_REQUEST";
export const FETCH_MOVIE_DETAILS_SUCCESS = "FETCH_MOVIE_DETAILS_SUCCESS";
export const FETCH_MOVIE_DETAILS_FAILURE = "FETCH_MOVIE_DETAILS_FAILURE";

export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE";

export const FETCH_UPCOMING_MOVIES_REQUEST = "FETCH_UPCOMING_MOVIES_REQUEST";
export const FETCH_UPCOMING_MOVIES_SUCCESS = "FETCH_UPCOMING_MOVIES_SUCCESS";
export const FETCH_UPCOMING_MOVIES_FAILURE = "FETCH_UPCOMING_MOVIES_FAILURE";

export const FETCH_UPCOMING_MOVIE_DETAILS_REQUEST =
  "FETCH_UPCOMING_MOVIE_DETAILS_REQUEST";
export const FETCH_UPCOMING_MOVIE_DETAILS_SUCCESS =
  "FETCH_UPCOMING_MOVIE_DETAILS_SUCCESS";
export const FETCH_UPCOMING_MOVIE_DETAILS_FAILURE =
  "FETCH_UPCOMING_MOVIE_DETAILS_FAILURE";

export const SEARCH_UPCOMING_MOVIES_REQUEST = "SEARCH_UPCOMING_MOVIES_REQUEST";
export const SEARCH_UPCOMING_MOVIES_SUCCESS = "SEARCH_UPCOMING_MOVIES_SUCCESS";
export const SEARCH_UPCOMING_MOVIES_FAILURE = "SEARCH_UPCOMING_MOVIES_FAILURE";

export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";

export const SEARCH_EVENTS_REQUEST = "SEARCH_EVENTS_REQUEST";
export const SEARCH_EVENTS_SUCCESS = "SEARCH_EVENTS_SUCCESS";
export const SEARCH_EVENTS_FAILURE = "SEARCH_EVENTS_FAILURE";

export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST";
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS";
export const BOOK_TICKET_FAILURE = "BOOK_TICKET_FAILURE";

export const FETCH_BOOKINGS_REQUEST = "FETCH_BOOKINGS_REQUEST";
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAILURE = "FETCH_BOOKINGS_FAILURE";
